### ISSUE TITLE
"RelatedContents" header support

### ISSUE THREAD

**Issue by DBC-Works** [DBC-Works/BoothCMS#2]
Add "RelatedContents" header support. This header allows manual specification of related contents.

```
relation: 
  - 
    href: ...
    description: ...
```
